image: aylacn/android-build:28-jdk8

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - echo "CI_BUILDS_DIR - ${CI_BUILDS_DIR}"
  - echo "CI_PROJECT_ID - ${CI_PROJECT_ID}"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - lint
  - assemble
  - publish

job_lint:
  stage: lint
  #  only:
  #    - /^issue[-|/].+$/
  #    - /^feature[-|/].+$/
  #    - /^bugfix[-|/].+$/
  script:
    - echo "开始Lint"
    - gradle -Pci --console=plain :app:lint -PbuildDir=lint
    - echo "Lint结束"
  tags:
    - docker
    - android
    - hk

job_signing_prepare:
  stage: signing_prepare
  script:
    - echo "开始创建签名文件"
    - echo $JKS_BASE64 | base64 -d > ayla_test.jks
    - echo "storePassword=$storePassword" > siging.properties
    - echo "keyPassword=$keyPassword" >> siging.properties
    - echo "keyAlias=$keyAlias" >> siging.properties
    - echo "创建签名文件结束"
  only:
    - master
  artifacts:
    paths:
      - ayla_test.jks
      - siging.properties
  tags:
    - android


job_assemble:
  stage: assemble
  only:
    - master
    - prod
  script:
    - echo "开始打包"
    - gradle assembleProdRelease
    - echo "打包结束"
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - docker
    - android
    - hk

job_publish:
  stage: publish
  only:
    refs:
      - prod
      - master
    changes:
      - CHANGELOG.MD
  script:
    - echo "开始上传APP到蒲公英"
    - buildUpdateDescription=$(cat CHANGELOG.MD)
    - echo "buildUpdateDescription=$buildUpdateDescription"
    - curl -F 'file=@app/build/outputs/apk/prod/release/app-prod-release.apk' -F '_api_key=$pgyer_api_key'   https://www.pgyer.com/apiv2/app/upload
    - echo "上传APP到蒲公英结束"
  tags:
    - docker
    - android
    - hk
