image: ayalcn/android-build:29-jdk8

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - echo "CI_BUILDS_DIR - ${CI_BUILDS_DIR}"
  - echo "CI_PROJECT_ID - ${CI_PROJECT_ID}"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - check
  - build

lintDebug:
  stage: check
  only:
    - /^issue[-|/].+$/
    - /^feature[-|/].+$/
    - /^bugfix[-|/].+$/
  script:
    - gradle -Pci --console=plain :app:lintDebug -PbuildDir=lint
  tags:
    - docker
    - android
    - hk

testDebug:
  stage: check
  only:
    - /^issue[-|/].+$/
    - /^feature[-|/].+$/
    - /^bugfix[-|/].+$/
  script:
    - gradle -Pci --console=plain :app:testDebug
  tags:
    - docker
    - android
    - hk

assembleDebug:
  stage: build
  only:
    - master
  script:
    - gradle assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug
  tags:
    - docker
    - android
    - hk
