image: aylacn/android-build:28-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # 禁用 gradle 守护进程

before_script:
  - chmod +x gradlew
  - export ANDROID_HOME=/Users/fanchunlei/Library/Android/sdk

stages:
  - lint
  - signing_prepare
  - assemble
  - publish

job_lint:
  stage: lint
  #  only:
  #    - /^issue[-|/].+$/
  #    - /^feature[-|/].+$/
  #    - /^bugfix[-|/].+$/
  script:
    - echo "开始Lint"
    - ./gradlew -Pci --console=plain :app:lint -PbuildDir=lint
    - echo "Lint结束"
  tags:
    - iOS
  except:
    refs:
      - master

job_signing_prepare:
  stage: signing_prepare
  script:
    - echo "开始创建签名文件"
    - echo $JKS_BASE64 | base64 -d > ayla_test.jks
    - echo "storePassword=$storePassword" > signing.properties
    - echo "keyPassword=$keyPassword" >> signing.properties
    - echo "keyAlias=$keyAlias" >> signing.properties
    - echo "创建签名文件结束"
  only:
    refs:
      - master
    changes:
      - CHANGELOG.MD
  artifacts:
    paths:
      - ayla_test.jks
      - signing.properties
  tags:
    - iOS

job_assemble:
  stage: assemble
  only:
    - master
    - prod
  script:
    - echo "开始打包"
    - ./gradlew :app:assembleRelease
    - echo "打包结束"
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - iOS

job_publish:
  stage: publish
  only:
    refs:
      - prod
    changes:
      - CHANGELOG.MD
  script:
    - echo "开始上传APP到蒲公英"
    - echo "pgyer_api_key=$pgyer_api_key"
    - buildUpdateDescription=$(cat CHANGELOG.MD)
    - echo "buildUpdateDescription=$buildUpdateDescription"
    - curl -F 'file=@app/build/outputs/apk/prod/release/app-prod-release.apk' -F "_api_key=$pgyer_api_key" -F "buildUpdateDescription=$buildUpdateDescription"  https://www.pgyer.com/apiv2/app/upload
    - echo "上传APP到蒲公英结束"
  tags:
    - iOS
